//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBanner
    {
        public int bannerId { get; set; }
        public string bannerTitle { get; set; }
        public string descr { get; set; }
        public string bannerSmallTitle { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> addedOn { get; set; }
        public string bannerImage { get; set; }
    }
}
