//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbrand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblbrand()
        {
            this.tblProducts = new HashSet<tblProduct>();
        }
    
        public int brId { get; set; }
        public string brName { get; set; }
        public string brImage { get; set; }
        public Nullable<bool> isDel { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts { get; set; }
    }
}
