//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCart
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public string userType { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> proId { get; set; }
        public Nullable<int> proAttrId { get; set; }
        public Nullable<System.DateTime> addedOn { get; set; }
    
        public virtual tblProAttr tblProAttr { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public string proName { get; internal set; }
        public string proImage { get; internal set; }
        public string size { get; internal set; }
        public string colName { get; internal set; }
        public decimal price { get; internal set; }
        public string proAttrImage { get; internal set; }
        public string color { get; internal set; }
    }
}
