//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
        }
    
        public int id { get; set; }
        public Nullable<int> customersId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pincode { get; set; }
        public Nullable<int> orderStatus { get; set; }
        public string paymentType { get; set; }
        public string paymentStatus { get; set; }
        public string paymentId { get; set; }
        public string txnId { get; set; }
        public Nullable<decimal> totalAmt { get; set; }
        public string trackDetails { get; set; }
        public Nullable<System.DateTime> added_on { get; set; }
        public Nullable<bool> isDel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
        public virtual tblRegistration tblRegistration { get; set; }
        public virtual tblOrderStatu tblOrderStatu { get; set; }
    }
}
