//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        public int odId { get; set; }
        public Nullable<int> orders_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> products_attr_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblProAttr tblProAttr { get; set; }
    }
}
