//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblCarts = new HashSet<tblCart>();
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
            this.tblProAttrs = new HashSet<tblProAttr>();
            this.tblProImages = new HashSet<tblProImage>();
        }
    
        public int proId { get; set; }
        public string proName { get; set; }
        public string proImage { get; set; }
        public Nullable<int> catId { get; set; }
        public Nullable<int> subCatId { get; set; }
        public string model { get; set; }
        public Nullable<int> bId { get; set; }
        public string description { get; set; }
        public string shortDesc { get; set; }
        public string uses { get; set; }
        public string addInfo { get; set; }
        public Nullable<decimal> proPrice { get; set; }
        public Nullable<decimal> proDisPrice { get; set; }
        public Nullable<int> isPromo { get; set; }
        public Nullable<int> isFeatured { get; set; }
        public Nullable<int> isTranding { get; set; }
        public Nullable<int> isDiscounted { get; set; }
        public Nullable<System.DateTime> addDateTime { get; set; }
        public Nullable<bool> isDel { get; set; }
    
        public virtual tblbrand tblbrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCart> tblCarts { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProAttr> tblProAttrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProImage> tblProImages { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
