//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProAttr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProAttr()
        {
            this.tblCarts = new HashSet<tblCart>();
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
        }
    
        public int proAttrId { get; set; }
        public Nullable<int> proId { get; set; }
        public string proAttrImage { get; set; }
        public Nullable<int> colorId { get; set; }
        public Nullable<int> qty { get; set; }
        public string size { get; set; }
        public Nullable<bool> isDel { get; set; }
        public Nullable<System.DateTime> addDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCart> tblCarts { get; set; }
        public virtual tblColor tblColor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
